import "./globals.css";
import type { Metadata } from "next";
import AuthContext from "@/context/AuthContext";
import SWRConfigContext from "@/context/SWRConfigContext";
import Navbar from "@/components/Navbart";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="w-full bg-neutral-50">
        <div id="portal">
          <AuthContext>
            <header className="sticky top-0 bg-white z-10 border-b">
              <div className="max-w-screen-xl mx-auto py-3">
                <Navbar />
              </div>
            </header>
            <main className="max-w-screen-xl mx-auto">
              <SWRConfigContext>{children}</SWRConfigContext>
            </main>
          </AuthContext>
        </div>
      </body>
    </html>
  );
}
